name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install Docker
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker.io
      #     sudo systemctl start docker
      #     sudo systemctl enable docker

      # - name: Add user to the Docker group
      #   run: |
      #     sudo usermod -aG docker $USER
      #     newgrp docker

      - name: Check Docker Version
        run: docker -v

      # - name: Reset Docker Buildx
      #   run: |
      #     docker buildx rm default || true
      #     docker buildx create --use

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        # uses: docker/login-action@v3
        # with:
        #   username: ${{ secrets.DOCKER_USERNAME }}
        #   password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image using Buildx
        run: |
          sudo docker buildx build -t anwarulhaque/foodie:latest --push .

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t anwarulhaque/foodie:latest .
      #     docker push anwarulhaque/foodie:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    
      - name: Deploy to EC2
        run: |
          sudo docker pull anwarulhaque/foodie:latest
          touch .env
          echo "${{secrets.DB_URL}}" > .env
          echo "${{secrets.PORT}}" > .env
          
      - name: Docker Compose  
        run: |
          sudo docker-compose down
          sudo docker-compose up -d




